package calculadoradecimales;

import Analizadores.Analizador_Lexico;
import Analizadores.analisis_sintactico;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.StringReader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tote
 */
public class Ventana extends javax.swing.JFrame {

    String concatenar = "";

    /**
     * Creates new form Ventana
     */
    public void Teclado() {

    }

    public Ventana() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
         jPanel1.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        txtSalida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnNumero1 = new javax.swing.JButton();
        btnNumero2 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnNumero3 = new javax.swing.JButton();
        btnNumero4 = new javax.swing.JButton();
        btnNumero5 = new javax.swing.JButton();
        btnNumero6 = new javax.swing.JButton();
        btnNumero7 = new javax.swing.JButton();
        btnNumero8 = new javax.swing.JButton();
        btnNumero9 = new javax.swing.JButton();
        btnNumero0 = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnPor = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnParC = new javax.swing.JButton();
        btnParA = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora ");
        setLocation(new java.awt.Point(1800, 250));
        setResizable(false);

        jButton1.setText("Compilar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNumero1.setText("1");
        btnNumero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero1MouseClicked(evt);
            }
        });

        btnNumero2.setText("2");
        btnNumero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero2MouseClicked(evt);
            }
        });

        btnSuma.setText("+");
        btnSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSumaMouseClicked(evt);
            }
        });

        btnNumero3.setText("3");
        btnNumero3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero3MouseClicked(evt);
            }
        });

        btnNumero4.setText("4");
        btnNumero4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero4MouseClicked(evt);
            }
        });

        btnNumero5.setText("5");
        btnNumero5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero5MouseClicked(evt);
            }
        });

        btnNumero6.setText("6");
        btnNumero6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero6MouseClicked(evt);
            }
        });
        btnNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero6ActionPerformed(evt);
            }
        });

        btnNumero7.setText("7");
        btnNumero7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero7MouseClicked(evt);
            }
        });

        btnNumero8.setText("8");
        btnNumero8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero8MouseClicked(evt);
            }
        });

        btnNumero9.setText("9");
        btnNumero9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero9MouseClicked(evt);
            }
        });

        btnNumero0.setText("0");
        btnNumero0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNumero0MouseClicked(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosMouseClicked(evt);
            }
        });

        btnPor.setText("*");
        btnPor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPorMouseClicked(evt);
            }
        });

        btnDivision.setText("/");
        btnDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisionMouseClicked(evt);
            }
        });

        btnParC.setText(")");
        btnParC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnParCMouseClicked(evt);
            }
        });

        btnParA.setText("(");
        btnParA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnParAMouseClicked(evt);
            }
        });

        btnPunto.setText(".");
        btnPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPuntoMouseClicked(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        btnClear.setText("C");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNumero0)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNumero7)
                                .addGap(18, 18, 18)
                                .addComponent(btnNumero8)))
                        .addGap(18, 18, 18)
                        .addComponent(btnNumero9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPor, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnNumero4)
                            .addGap(18, 18, 18)
                            .addComponent(btnNumero5)
                            .addGap(18, 18, 18)
                            .addComponent(btnNumero6)
                            .addGap(18, 18, 18)
                            .addComponent(btnMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnNumero1)
                            .addGap(18, 18, 18)
                            .addComponent(btnNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnNumero3)
                            .addGap(18, 18, 18)
                            .addComponent(btnSuma))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnParC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero1)
                    .addComponent(btnNumero2)
                    .addComponent(btnSuma)
                    .addComponent(btnNumero3)
                    .addComponent(btnParA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNumero5)
                        .addComponent(btnNumero6)
                        .addComponent(btnMenos)
                        .addComponent(btnParC))
                    .addComponent(btnNumero4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero7)
                    .addComponent(btnNumero8)
                    .addComponent(btnNumero9)
                    .addComponent(btnPor)
                    .addComponent(btnPunto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(btnNumero0))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDivision)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel1.setText("Entrada");

        jLabel2.setText("Salida");

        jButton2.setText("Integrantes");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Calculadora");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String datos = txtEntrada.getText();
        Analizador_Lexico lexico = new Analizador_Lexico(new BufferedReader(new StringReader(datos)));
        analisis_sintactico sintactico = new analisis_sintactico(lexico);

        try {
            sintactico.parse();
            String output = Double.toString(sintactico.resultado); // la variable resultado la convertimos 
            // en string.
            txtSalida.setText(output);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNumero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero1MouseClicked
        System.out.println("El valor es:" + "1");
        String valor1 = "1";
        concatenar = concatenar.concat(valor1);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero1MouseClicked

    private void btnNumero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero2MouseClicked
        System.out.println("El valor es:" + "2");
        String valor2 = "2";
        concatenar = concatenar.concat(valor2);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero2MouseClicked

    private void btnSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumaMouseClicked
        System.out.println("El valor es:" + "+");
        String suma = "+";
        concatenar = concatenar.concat(suma);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnSumaMouseClicked

    private void btnNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNumero6ActionPerformed

    private void btnNumero3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero3MouseClicked
        System.out.println("El valor es:" + "3");
        String vslor3 = "3";
        concatenar = concatenar.concat(vslor3);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero3MouseClicked

    private void btnNumero4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero4MouseClicked
        System.out.println("El valor es:" + "4");
        String vslor4 = "4";
        concatenar = concatenar.concat(vslor4);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero4MouseClicked

    private void btnNumero5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero5MouseClicked
        System.out.println("El valor es:" + "5");
        String vslor5 = "5";
        concatenar = concatenar.concat(vslor5);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero5MouseClicked

    private void btnNumero6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero6MouseClicked
        System.out.println("El valor es:" + "6");
        String vslor6 = "6";
        concatenar = concatenar.concat(vslor6);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero6MouseClicked

    private void btnNumero7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero7MouseClicked
        System.out.println("El valor es:" + "7");
        String vslor6 = "6";
        concatenar = concatenar.concat(vslor6);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero7MouseClicked

    private void btnNumero8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero8MouseClicked
        System.out.println("El valor es:" + "8");
        String vslor8 = "8";
        concatenar = concatenar.concat(vslor8);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero8MouseClicked

    private void btnNumero9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero9MouseClicked
        System.out.println("El valor es:" + "9");
        String valor9 = "9";
        concatenar = concatenar.concat(valor9);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero9MouseClicked

    private void btnNumero0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNumero0MouseClicked
        System.out.println("El valor es:" + "0");
        String vslor0 = "0";
        concatenar = concatenar.concat(vslor0);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnNumero0MouseClicked

    private void btnMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosMouseClicked
        System.out.println("El valor es:" + "-");
        String menos = "-";
        concatenar = concatenar.concat(menos);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnMenosMouseClicked

    private void btnPorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPorMouseClicked
        System.out.println("El valor es:" + "*");
        String por = "*";
        concatenar = concatenar.concat(por);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnPorMouseClicked

    private void btnDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseClicked
        System.out.println("El valor es:" + "/");
        String division = "/";
        concatenar = concatenar.concat(division);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnDivisionMouseClicked

    private void btnParCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParCMouseClicked
        System.out.println("El valor es:" + ")");
        String parC = ")";
        concatenar = concatenar.concat(parC);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnParCMouseClicked

    private void btnParAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnParAMouseClicked
        System.out.println("El valor es:" + "(");
        String parA = "(";
        concatenar = concatenar.concat(parA);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnParAMouseClicked

    private void btnPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPuntoMouseClicked
        System.out.println("El valor es:" + ".");
        String punto = ".";
        concatenar = concatenar.concat(punto);
        txtEntrada.setText(concatenar);
    }//GEN-LAST:event_btnPuntoMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        txtEntrada.setText("");
        txtSalida.setText("");
        concatenar="";
    }//GEN-LAST:event_btnClearMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        new Integrantes().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnNumero0;
    private javax.swing.JButton btnNumero1;
    private javax.swing.JButton btnNumero2;
    private javax.swing.JButton btnNumero3;
    private javax.swing.JButton btnNumero4;
    private javax.swing.JButton btnNumero5;
    private javax.swing.JButton btnNumero6;
    private javax.swing.JButton btnNumero7;
    private javax.swing.JButton btnNumero8;
    private javax.swing.JButton btnNumero9;
    private javax.swing.JButton btnParA;
    private javax.swing.JButton btnParC;
    private javax.swing.JButton btnPor;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
